### PR TITLE
Set up GitHub Pages

### PR DESCRIPTION
**Pull request by krlmlr**
with a reference index that distinguishes between vector functions and everything else.

To preview, run `pkgdown::build_site()` locally.

To switch, you need to run `git push origin :gh-pages` to erase the old webpage. If you want to keep a backup:

```
git worktree add website gh-pages
cd website
git branch -m website
git push -u origin HEAD
# switch GitHub Pages to serve website branch (possible now)
git push origin :gh-pages
# switch GitHub Pages to serve gh-pages branch
```

I'm not sure contributor access will help here, I can't seem to do these actions as a contributor.

### CODE REVIEW

**Comment by renkun-ken** [comment]
Thanks for the nice work!

I sent you an invitation to this repo as a collaborator. Please feel free to adapt the github pages for this.

**Comment by krlmlr** [comment]
The URL https://renkun.me/formattable now shows the pkgdown website. The old contents are stored in the new `website` branch. If you don't like this change, please change the GitHub Pages source to use the `website` branch.

**Comment by krlmlr** [comment]
Thanks for the invite!

**Comment by renkun-ken** [comment]
Thanks! Definitely like the changes!

**Pull request merged**
