### PR TITLE
add conversion to htmlwidget

### PR DESCRIPTION
**Pull request by timelyportfolio**
Add conversion to `htmlwidget` as discussed in #3, #6, & #7.  The new function `as.htmlwidget` will convert `formattable` objects into `htmlwidgets` so they can be rendered in `interactive()==TRUE` contexts.

`formattable` will also attempt to auto-convert to `htmlwidgets` if `interactive == TRUE` contexts unless `format` is explicitly something other than `NULL` or `markdown`.

### CODE REVIEW

**Comment by renkun-ken** [comment]
Thanks!

**Comment by renkun-ken** [comment]
When I'm building the package, I get the following error when I render the vignette:

```
==> devtools::document(roclets=c('rd', 'collate', 'namespace', 'vignette'))

Updating formattable documentation
Loading formattable
Writing as.htmlwidget.Rd
Writing as.htmlwidget.formattable.Rd
Writing percent.Rd
Writing comma.Rd
Writing currency.Rd
Writing accounting.Rd
Writing scientific.Rd
Writing prefix.Rd
Writing suffix.Rd
Writing formattable.Rd
Writing is.formattable.Rd
Writing formattable.default.Rd
Writing formattable.logical.Rd
Writing formattable.factor.Rd
Writing formattable.Date.Rd
Writing formattable.POSIXct.Rd
Writing formattable.POSIXlt.Rd
Skipping invalid path:  stats median.Rd 
Skipping invalid path:  stats quantile.Rd 
Writing format_table.Rd
Writing formattable.data.frame.Rd
Writing formatter.Rd
Writing color_tile.Rd
Writing color_bar.Rd
Writing color_text.Rd
Writing formattable-package.Rd
Writing style.Rd
Writing icontext.Rd
Writing gradient.Rd
Writing csscolor.Rd
Writing vmap.Rd
Writing qrank.Rd
Writing normalize.Rd
Writing NAMESPACE
Updating vignettes
Rebuilding Formattable_htmlwidget.Rmd
pandoc.exe: Could not fetch C:\Users\Kun\AppData\Local\Temp\Rtmp6zDX35\widgetbinding2b84a3964d3\formattable_widget.js
C:\Users\Kun\AppData\Local\Temp\Rtmp6zDX35\widgetbinding2b84a3964d3\formattable_widget.js: openBinaryFile: does not exist (No such file or directory)
Error: pandoc document conversion failed with error 67
In addition: Warning message:
running command '"C:/Users/Kun/AppData/Local/Pandoc/pandoc" Formattable_htmlwidget.utf8.md --to html --from markdown+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash-implicit_figures --output Formattable_htmlwidget.html --smart --email-obfuscation none --self-contained --standalone --section-divs --template "C:\Users\Kun\Documents\R\win-library\3.2\rmarkdown\rmd\h\default.html" --css "C:\Users\Kun\Documents\R\win-library\3.2\rmarkdown\rmarkdown\templates\html_vignette\resources\vignette.css" --include-in-header "C:\Users\Kun\AppData\Local\Temp\Rtmp6zDX35\rmarkdown-str2b8429632b0.html" --mathjax --variable "mathjax-url:https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML" --highlight-style pygments' had status 67 
Execution halted

Exited with status 1.
```

**Comment by renkun-ken** [comment]
Thanks for the great writing and demos but I temporarily removed the vignette from the package and make it build first. The contents are great materials to demo experimental features/usages but I'm not sure if it's appropriate to show up as a package vignette especially when it requires a number of packages that should be added to `Suggests` to pass the package check.

**Comment by timelyportfolio** [comment]
That makes sense.  I'll try to rework to a more minimal form.

**Pull request merged**
